# Generated by Django 3.2.13 on 2022-07-11 13:52

from django.db import migrations, models
import django.db.models.deletion
import myproject.apps.store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('is_featured', models.BooleanField(default=False)),
                ('picture', models.ImageField(null=True, upload_to=myproject.apps.store.models.upload_to, verbose_name='Picture')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='store.payment', verbose_name='Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
