# Generated by Django 3.2.13 on 2022-07-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(max_length=200, verbose_name='Number'),
        ),
    ]
