# Generated by Django 3.2.13 on 2022-06-30 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='../../site_static/img')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='../../site_static/img')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
