# Generated by Django 3.2.13 on 2022-06-30 15:48

from django.db import migrations, models
import myproject.apps.webpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_testimoni_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimoni',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimoni',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='testimoni',
            name='picture',
            field=models.ImageField(default='', upload_to=myproject.apps.webpage.models.upload_to, verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
